apiVersion: v1
kind: Service
metadata:
  labels:
    app: streamer
  name: streamer
  namespace: cnp-streamer
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: streamer
  type: LoadBalancer