# build stage
FROM golang:alpine AS build-env
ADD . /go/src/github.com/yolo3301/cnp
RUN apk add --update alpine-sdk
RUN cd /go/src/github.com/yolo3301/cnp && go build -v -i -o ./bin/streamer ./cmd/streamer

# final stage
FROM alpine
WORKDIR /app
COPY --from=build-env /go/src/github.com/yolo3301/cnp/bin/streamer /app/
EXPOSE 8080
CMD ["./streamer"]