// Code generated by protoc-gen-go. DO NOT EDIT.
// source: streamer_agent.proto

package streamer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StreamNotificationRequest_Status int32

const (
	StreamNotificationRequest_OK             StreamNotificationRequest_Status = 0
	StreamNotificationRequest_INTERNAL_ERROR StreamNotificationRequest_Status = 1
	StreamNotificationRequest_BAD_REQUEST    StreamNotificationRequest_Status = 2
)

var StreamNotificationRequest_Status_name = map[int32]string{
	0: "OK",
	1: "INTERNAL_ERROR",
	2: "BAD_REQUEST",
}
var StreamNotificationRequest_Status_value = map[string]int32{
	"OK":             0,
	"INTERNAL_ERROR": 1,
	"BAD_REQUEST":    2,
}

func (x StreamNotificationRequest_Status) String() string {
	return proto.EnumName(StreamNotificationRequest_Status_name, int32(x))
}
func (StreamNotificationRequest_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_streamer_agent_e7dd3b6be7dc4e34, []int{1, 0}
}

type KeyValue struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyValue) Reset()         { *m = KeyValue{} }
func (m *KeyValue) String() string { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()    {}
func (*KeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_streamer_agent_e7dd3b6be7dc4e34, []int{0}
}
func (m *KeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValue.Unmarshal(m, b)
}
func (m *KeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValue.Marshal(b, m, deterministic)
}
func (dst *KeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValue.Merge(dst, src)
}
func (m *KeyValue) XXX_Size() int {
	return xxx_messageInfo_KeyValue.Size(m)
}
func (m *KeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValue proto.InternalMessageInfo

func (m *KeyValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type StreamNotificationRequest struct {
	RequestId            string           `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	First                bool             `protobuf:"varint,2,opt,name=first,proto3" json:"first,omitempty"`
	FinalStatus          int32            `protobuf:"varint,3,opt,name=final_status,json=finalStatus,proto3" json:"final_status,omitempty"`
	AgentNote            []byte           `protobuf:"bytes,4,opt,name=agent_note,json=agentNote,proto3" json:"agent_note,omitempty"`
	Request              *HttpRequestInfo `protobuf:"bytes,5,opt,name=request,proto3" json:"request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *StreamNotificationRequest) Reset()         { *m = StreamNotificationRequest{} }
func (m *StreamNotificationRequest) String() string { return proto.CompactTextString(m) }
func (*StreamNotificationRequest) ProtoMessage()    {}
func (*StreamNotificationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_streamer_agent_e7dd3b6be7dc4e34, []int{1}
}
func (m *StreamNotificationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamNotificationRequest.Unmarshal(m, b)
}
func (m *StreamNotificationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamNotificationRequest.Marshal(b, m, deterministic)
}
func (dst *StreamNotificationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamNotificationRequest.Merge(dst, src)
}
func (m *StreamNotificationRequest) XXX_Size() int {
	return xxx_messageInfo_StreamNotificationRequest.Size(m)
}
func (m *StreamNotificationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamNotificationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamNotificationRequest proto.InternalMessageInfo

func (m *StreamNotificationRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *StreamNotificationRequest) GetFirst() bool {
	if m != nil {
		return m.First
	}
	return false
}

func (m *StreamNotificationRequest) GetFinalStatus() int32 {
	if m != nil {
		return m.FinalStatus
	}
	return 0
}

func (m *StreamNotificationRequest) GetAgentNote() []byte {
	if m != nil {
		return m.AgentNote
	}
	return nil
}

func (m *StreamNotificationRequest) GetRequest() *HttpRequestInfo {
	if m != nil {
		return m.Request
	}
	return nil
}

type HttpRequestInfo struct {
	Method               string                   `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	ReqUri               string                   `protobuf:"bytes,2,opt,name=req_uri,json=reqUri,proto3" json:"req_uri,omitempty"`
	Header               []*KeyValue              `protobuf:"bytes,3,rep,name=header,proto3" json:"header,omitempty"`
	Payload              *HttpRequestInfo_Payload `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *HttpRequestInfo) Reset()         { *m = HttpRequestInfo{} }
func (m *HttpRequestInfo) String() string { return proto.CompactTextString(m) }
func (*HttpRequestInfo) ProtoMessage()    {}
func (*HttpRequestInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_streamer_agent_e7dd3b6be7dc4e34, []int{2}
}
func (m *HttpRequestInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpRequestInfo.Unmarshal(m, b)
}
func (m *HttpRequestInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpRequestInfo.Marshal(b, m, deterministic)
}
func (dst *HttpRequestInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpRequestInfo.Merge(dst, src)
}
func (m *HttpRequestInfo) XXX_Size() int {
	return xxx_messageInfo_HttpRequestInfo.Size(m)
}
func (m *HttpRequestInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpRequestInfo.DiscardUnknown(m)
}

var xxx_messageInfo_HttpRequestInfo proto.InternalMessageInfo

func (m *HttpRequestInfo) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *HttpRequestInfo) GetReqUri() string {
	if m != nil {
		return m.ReqUri
	}
	return ""
}

func (m *HttpRequestInfo) GetHeader() []*KeyValue {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *HttpRequestInfo) GetPayload() *HttpRequestInfo_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

type HttpRequestInfo_Payload struct {
	FinalSize            int64    `protobuf:"varint,1,opt,name=final_size,json=finalSize,proto3" json:"final_size,omitempty"`
	Sha256Hash           string   `protobuf:"bytes,2,opt,name=sha256_hash,json=sha256Hash,proto3" json:"sha256_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HttpRequestInfo_Payload) Reset()         { *m = HttpRequestInfo_Payload{} }
func (m *HttpRequestInfo_Payload) String() string { return proto.CompactTextString(m) }
func (*HttpRequestInfo_Payload) ProtoMessage()    {}
func (*HttpRequestInfo_Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_streamer_agent_e7dd3b6be7dc4e34, []int{2, 0}
}
func (m *HttpRequestInfo_Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpRequestInfo_Payload.Unmarshal(m, b)
}
func (m *HttpRequestInfo_Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpRequestInfo_Payload.Marshal(b, m, deterministic)
}
func (dst *HttpRequestInfo_Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpRequestInfo_Payload.Merge(dst, src)
}
func (m *HttpRequestInfo_Payload) XXX_Size() int {
	return xxx_messageInfo_HttpRequestInfo_Payload.Size(m)
}
func (m *HttpRequestInfo_Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpRequestInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_HttpRequestInfo_Payload proto.InternalMessageInfo

func (m *HttpRequestInfo_Payload) GetFinalSize() int64 {
	if m != nil {
		return m.FinalSize
	}
	return 0
}

func (m *HttpRequestInfo_Payload) GetSha256Hash() string {
	if m != nil {
		return m.Sha256Hash
	}
	return ""
}

type StreamNotificationResult struct {
	AgentNote            []byte            `protobuf:"bytes,1,opt,name=agent_note,json=agentNote,proto3" json:"agent_note,omitempty"`
	Response             *HttpResponseInfo `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	DropTarget           *DropTarget       `protobuf:"bytes,3,opt,name=drop_target,json=dropTarget,proto3" json:"drop_target,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *StreamNotificationResult) Reset()         { *m = StreamNotificationResult{} }
func (m *StreamNotificationResult) String() string { return proto.CompactTextString(m) }
func (*StreamNotificationResult) ProtoMessage()    {}
func (*StreamNotificationResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_streamer_agent_e7dd3b6be7dc4e34, []int{3}
}
func (m *StreamNotificationResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamNotificationResult.Unmarshal(m, b)
}
func (m *StreamNotificationResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamNotificationResult.Marshal(b, m, deterministic)
}
func (dst *StreamNotificationResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamNotificationResult.Merge(dst, src)
}
func (m *StreamNotificationResult) XXX_Size() int {
	return xxx_messageInfo_StreamNotificationResult.Size(m)
}
func (m *StreamNotificationResult) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamNotificationResult.DiscardUnknown(m)
}

var xxx_messageInfo_StreamNotificationResult proto.InternalMessageInfo

func (m *StreamNotificationResult) GetAgentNote() []byte {
	if m != nil {
		return m.AgentNote
	}
	return nil
}

func (m *StreamNotificationResult) GetResponse() *HttpResponseInfo {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *StreamNotificationResult) GetDropTarget() *DropTarget {
	if m != nil {
		return m.DropTarget
	}
	return nil
}

type DropTarget struct {
	FileTarget           *DropTarget_FileTarget `protobuf:"bytes,1,opt,name=file_target,json=fileTarget,proto3" json:"file_target,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *DropTarget) Reset()         { *m = DropTarget{} }
func (m *DropTarget) String() string { return proto.CompactTextString(m) }
func (*DropTarget) ProtoMessage()    {}
func (*DropTarget) Descriptor() ([]byte, []int) {
	return fileDescriptor_streamer_agent_e7dd3b6be7dc4e34, []int{4}
}
func (m *DropTarget) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DropTarget.Unmarshal(m, b)
}
func (m *DropTarget) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DropTarget.Marshal(b, m, deterministic)
}
func (dst *DropTarget) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DropTarget.Merge(dst, src)
}
func (m *DropTarget) XXX_Size() int {
	return xxx_messageInfo_DropTarget.Size(m)
}
func (m *DropTarget) XXX_DiscardUnknown() {
	xxx_messageInfo_DropTarget.DiscardUnknown(m)
}

var xxx_messageInfo_DropTarget proto.InternalMessageInfo

func (m *DropTarget) GetFileTarget() *DropTarget_FileTarget {
	if m != nil {
		return m.FileTarget
	}
	return nil
}

type DropTarget_FileTarget struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DropTarget_FileTarget) Reset()         { *m = DropTarget_FileTarget{} }
func (m *DropTarget_FileTarget) String() string { return proto.CompactTextString(m) }
func (*DropTarget_FileTarget) ProtoMessage()    {}
func (*DropTarget_FileTarget) Descriptor() ([]byte, []int) {
	return fileDescriptor_streamer_agent_e7dd3b6be7dc4e34, []int{4, 0}
}
func (m *DropTarget_FileTarget) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DropTarget_FileTarget.Unmarshal(m, b)
}
func (m *DropTarget_FileTarget) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DropTarget_FileTarget.Marshal(b, m, deterministic)
}
func (dst *DropTarget_FileTarget) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DropTarget_FileTarget.Merge(dst, src)
}
func (m *DropTarget_FileTarget) XXX_Size() int {
	return xxx_messageInfo_DropTarget_FileTarget.Size(m)
}
func (m *DropTarget_FileTarget) XXX_DiscardUnknown() {
	xxx_messageInfo_DropTarget_FileTarget.DiscardUnknown(m)
}

var xxx_messageInfo_DropTarget_FileTarget proto.InternalMessageInfo

func (m *DropTarget_FileTarget) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type HttpResponseInfo struct {
	HttpStatus           int32                     `protobuf:"varint,1,opt,name=http_status,json=httpStatus,proto3" json:"http_status,omitempty"`
	Header               []*KeyValue               `protobuf:"bytes,2,rep,name=header,proto3" json:"header,omitempty"`
	Payload              *HttpResponseInfo_Payload `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *HttpResponseInfo) Reset()         { *m = HttpResponseInfo{} }
func (m *HttpResponseInfo) String() string { return proto.CompactTextString(m) }
func (*HttpResponseInfo) ProtoMessage()    {}
func (*HttpResponseInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_streamer_agent_e7dd3b6be7dc4e34, []int{5}
}
func (m *HttpResponseInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpResponseInfo.Unmarshal(m, b)
}
func (m *HttpResponseInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpResponseInfo.Marshal(b, m, deterministic)
}
func (dst *HttpResponseInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpResponseInfo.Merge(dst, src)
}
func (m *HttpResponseInfo) XXX_Size() int {
	return xxx_messageInfo_HttpResponseInfo.Size(m)
}
func (m *HttpResponseInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpResponseInfo.DiscardUnknown(m)
}

var xxx_messageInfo_HttpResponseInfo proto.InternalMessageInfo

func (m *HttpResponseInfo) GetHttpStatus() int32 {
	if m != nil {
		return m.HttpStatus
	}
	return 0
}

func (m *HttpResponseInfo) GetHeader() []*KeyValue {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *HttpResponseInfo) GetPayload() *HttpResponseInfo_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

type HttpResponseInfo_Payload struct {
	FileObject           *HttpResponseInfo_Payload_FileObject `protobuf:"bytes,1,opt,name=file_object,json=fileObject,proto3" json:"file_object,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *HttpResponseInfo_Payload) Reset()         { *m = HttpResponseInfo_Payload{} }
func (m *HttpResponseInfo_Payload) String() string { return proto.CompactTextString(m) }
func (*HttpResponseInfo_Payload) ProtoMessage()    {}
func (*HttpResponseInfo_Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_streamer_agent_e7dd3b6be7dc4e34, []int{5, 0}
}
func (m *HttpResponseInfo_Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpResponseInfo_Payload.Unmarshal(m, b)
}
func (m *HttpResponseInfo_Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpResponseInfo_Payload.Marshal(b, m, deterministic)
}
func (dst *HttpResponseInfo_Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpResponseInfo_Payload.Merge(dst, src)
}
func (m *HttpResponseInfo_Payload) XXX_Size() int {
	return xxx_messageInfo_HttpResponseInfo_Payload.Size(m)
}
func (m *HttpResponseInfo_Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpResponseInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_HttpResponseInfo_Payload proto.InternalMessageInfo

func (m *HttpResponseInfo_Payload) GetFileObject() *HttpResponseInfo_Payload_FileObject {
	if m != nil {
		return m.FileObject
	}
	return nil
}

type HttpResponseInfo_Payload_FileObject struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HttpResponseInfo_Payload_FileObject) Reset()         { *m = HttpResponseInfo_Payload_FileObject{} }
func (m *HttpResponseInfo_Payload_FileObject) String() string { return proto.CompactTextString(m) }
func (*HttpResponseInfo_Payload_FileObject) ProtoMessage()    {}
func (*HttpResponseInfo_Payload_FileObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_streamer_agent_e7dd3b6be7dc4e34, []int{5, 0, 0}
}
func (m *HttpResponseInfo_Payload_FileObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpResponseInfo_Payload_FileObject.Unmarshal(m, b)
}
func (m *HttpResponseInfo_Payload_FileObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpResponseInfo_Payload_FileObject.Marshal(b, m, deterministic)
}
func (dst *HttpResponseInfo_Payload_FileObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpResponseInfo_Payload_FileObject.Merge(dst, src)
}
func (m *HttpResponseInfo_Payload_FileObject) XXX_Size() int {
	return xxx_messageInfo_HttpResponseInfo_Payload_FileObject.Size(m)
}
func (m *HttpResponseInfo_Payload_FileObject) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpResponseInfo_Payload_FileObject.DiscardUnknown(m)
}

var xxx_messageInfo_HttpResponseInfo_Payload_FileObject proto.InternalMessageInfo

func (m *HttpResponseInfo_Payload_FileObject) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func init() {
	proto.RegisterType((*KeyValue)(nil), "streamer.KeyValue")
	proto.RegisterType((*StreamNotificationRequest)(nil), "streamer.StreamNotificationRequest")
	proto.RegisterType((*HttpRequestInfo)(nil), "streamer.HttpRequestInfo")
	proto.RegisterType((*HttpRequestInfo_Payload)(nil), "streamer.HttpRequestInfo.Payload")
	proto.RegisterType((*StreamNotificationResult)(nil), "streamer.StreamNotificationResult")
	proto.RegisterType((*DropTarget)(nil), "streamer.DropTarget")
	proto.RegisterType((*DropTarget_FileTarget)(nil), "streamer.DropTarget.FileTarget")
	proto.RegisterType((*HttpResponseInfo)(nil), "streamer.HttpResponseInfo")
	proto.RegisterType((*HttpResponseInfo_Payload)(nil), "streamer.HttpResponseInfo.Payload")
	proto.RegisterType((*HttpResponseInfo_Payload_FileObject)(nil), "streamer.HttpResponseInfo.Payload.FileObject")
	proto.RegisterEnum("streamer.StreamNotificationRequest_Status", StreamNotificationRequest_Status_name, StreamNotificationRequest_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StreamerAgentClient is the client API for StreamerAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StreamerAgentClient interface {
	OnNotification(ctx context.Context, in *StreamNotificationRequest, opts ...grpc.CallOption) (*StreamNotificationResult, error)
}

type streamerAgentClient struct {
	cc *grpc.ClientConn
}

func NewStreamerAgentClient(cc *grpc.ClientConn) StreamerAgentClient {
	return &streamerAgentClient{cc}
}

func (c *streamerAgentClient) OnNotification(ctx context.Context, in *StreamNotificationRequest, opts ...grpc.CallOption) (*StreamNotificationResult, error) {
	out := new(StreamNotificationResult)
	err := c.cc.Invoke(ctx, "/streamer.StreamerAgent/OnNotification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StreamerAgentServer is the server API for StreamerAgent service.
type StreamerAgentServer interface {
	OnNotification(context.Context, *StreamNotificationRequest) (*StreamNotificationResult, error)
}

func RegisterStreamerAgentServer(s *grpc.Server, srv StreamerAgentServer) {
	s.RegisterService(&_StreamerAgent_serviceDesc, srv)
}

func _StreamerAgent_OnNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StreamNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamerAgentServer).OnNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/streamer.StreamerAgent/OnNotification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamerAgentServer).OnNotification(ctx, req.(*StreamNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StreamerAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "streamer.StreamerAgent",
	HandlerType: (*StreamerAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnNotification",
			Handler:    _StreamerAgent_OnNotification_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "streamer_agent.proto",
}

func init() {
	proto.RegisterFile("streamer_agent.proto", fileDescriptor_streamer_agent_e7dd3b6be7dc4e34)
}

var fileDescriptor_streamer_agent_e7dd3b6be7dc4e34 = []byte{
	// 604 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x41, 0x4f, 0xdb, 0x4c,
	0x10, 0x65, 0x13, 0x30, 0xc9, 0x98, 0x0f, 0xa2, 0x15, 0xfa, 0x6a, 0x22, 0x55, 0x18, 0xf7, 0x12,
	0x55, 0x6a, 0x0e, 0x46, 0x70, 0x69, 0x0f, 0xa5, 0x22, 0x15, 0x11, 0x55, 0xd2, 0x6e, 0xa0, 0x97,
	0x1e, 0xac, 0x05, 0xaf, 0xf1, 0xb6, 0xc6, 0x6b, 0xd6, 0x9b, 0x4a, 0xd0, 0x7f, 0xd2, 0x5f, 0xd0,
	0x5f, 0xd8, 0x63, 0x55, 0x79, 0x77, 0x8d, 0xab, 0x94, 0x94, 0xdb, 0xcc, 0x9b, 0xd9, 0xe7, 0x99,
	0x37, 0x4f, 0x86, 0xed, 0x52, 0x49, 0x46, 0xaf, 0x99, 0x8c, 0xe8, 0x15, 0xcb, 0xd5, 0xb0, 0x90,
	0x42, 0x09, 0xdc, 0xa9, 0xd1, 0x20, 0x84, 0xce, 0x29, 0xbb, 0xfd, 0x48, 0xb3, 0x39, 0xc3, 0x3d,
	0x68, 0x7f, 0x61, 0xb7, 0x1e, 0xf2, 0xd1, 0xa0, 0x4b, 0xaa, 0x10, 0x6f, 0xc3, 0xda, 0xd7, 0xaa,
	0xe4, 0xb5, 0x34, 0x66, 0x92, 0xe0, 0x17, 0x82, 0x9d, 0x99, 0x26, 0x98, 0x08, 0xc5, 0x13, 0x7e,
	0x49, 0x15, 0x17, 0x39, 0x61, 0x37, 0x73, 0x56, 0x2a, 0xfc, 0x14, 0x40, 0x9a, 0x30, 0xe2, 0xb1,
	0x25, 0xeb, 0x5a, 0x64, 0x1c, 0x57, 0x94, 0x09, 0x97, 0xa5, 0xd2, 0x94, 0x1d, 0x62, 0x12, 0xbc,
	0x07, 0x1b, 0x09, 0xcf, 0x69, 0x16, 0x95, 0x8a, 0xaa, 0x79, 0xe9, 0xb5, 0x7d, 0x34, 0x58, 0x23,
	0xae, 0xc6, 0x66, 0x1a, 0xaa, 0x78, 0xf5, 0x0a, 0x51, 0x2e, 0x14, 0xf3, 0x56, 0x7d, 0x34, 0xd8,
	0x20, 0x5d, 0x8d, 0x4c, 0x84, 0x62, 0x78, 0x1f, 0xd6, 0xed, 0x47, 0xbc, 0x35, 0x1f, 0x0d, 0xdc,
	0x70, 0x67, 0x58, 0x2f, 0x39, 0x3c, 0x51, 0xaa, 0xb0, 0xe3, 0x8d, 0xf3, 0x44, 0x90, 0xba, 0x33,
	0x38, 0x00, 0xc7, 0xb2, 0x3b, 0xd0, 0x9a, 0x9e, 0xf6, 0x56, 0x30, 0x86, 0xcd, 0xf1, 0xe4, 0x6c,
	0x44, 0x26, 0x47, 0xef, 0xa2, 0x11, 0x21, 0x53, 0xd2, 0x43, 0x78, 0x0b, 0xdc, 0x37, 0x47, 0xc7,
	0x11, 0x19, 0x7d, 0x38, 0x1f, 0xcd, 0xce, 0x7a, 0xad, 0xe0, 0x27, 0x82, 0xad, 0x05, 0x4e, 0xfc,
	0x3f, 0x38, 0xd7, 0x4c, 0xa5, 0xa2, 0x5e, 0xd9, 0x66, 0xf8, 0x89, 0x9e, 0x2b, 0x9a, 0x4b, 0x6e,
	0x45, 0x74, 0x24, 0xbb, 0x39, 0x97, 0x1c, 0x3f, 0x07, 0x27, 0x65, 0x34, 0x66, 0xd2, 0x6b, 0xfb,
	0xed, 0x81, 0x1b, 0xe2, 0x66, 0xde, 0xfa, 0x22, 0xc4, 0x76, 0xe0, 0x97, 0xb0, 0x5e, 0xd0, 0xdb,
	0x4c, 0xd0, 0x58, 0x2f, 0xee, 0x86, 0x7b, 0x4b, 0x97, 0x1b, 0xbe, 0x37, 0x8d, 0xa4, 0x7e, 0xd1,
	0x1f, 0xc3, 0xba, 0xc5, 0x2a, 0x0d, 0xad, 0xcc, 0xfc, 0x8e, 0xe9, 0x41, 0xdb, 0xa4, 0x6b, 0x44,
	0xe6, 0x77, 0x0c, 0xef, 0x82, 0x5b, 0xa6, 0x34, 0x3c, 0x38, 0x8c, 0x52, 0x5a, 0xa6, 0x76, 0x5e,
	0x30, 0xd0, 0x09, 0x2d, 0xd3, 0xe0, 0x07, 0x02, 0xef, 0xa1, 0xcb, 0x97, 0xf3, 0x4c, 0x2d, 0x1c,
	0x08, 0x2d, 0x1e, 0xe8, 0x10, 0x3a, 0x92, 0x95, 0x85, 0xc8, 0x4b, 0x63, 0x27, 0x37, 0xec, 0x2f,
	0x2e, 0x61, 0xaa, 0xfa, 0x44, 0xf7, 0xbd, 0xf8, 0x00, 0xdc, 0x58, 0x8a, 0x22, 0x52, 0x54, 0x5e,
	0x31, 0xa5, 0x9d, 0xe1, 0x86, 0xdb, 0xcd, 0xd3, 0x63, 0x29, 0x8a, 0x33, 0x5d, 0x23, 0x10, 0xdf,
	0xc7, 0x41, 0x01, 0xd0, 0x54, 0xf0, 0x6b, 0x70, 0x13, 0x9e, 0xb1, 0x9a, 0x04, 0x69, 0x92, 0xdd,
	0x87, 0x48, 0x86, 0x6f, 0x79, 0xc6, 0x6a, 0xbe, 0xe4, 0x3e, 0xee, 0xfb, 0x00, 0x4d, 0x05, 0x63,
	0x58, 0x2d, 0xa8, 0x4a, 0xed, 0xad, 0x75, 0x1c, 0x7c, 0x6f, 0x41, 0x6f, 0x71, 0x8f, 0x4a, 0xd2,
	0x54, 0xa9, 0xa2, 0xf6, 0x35, 0xd2, 0xbe, 0x86, 0x0a, 0xb2, 0xc6, 0x6b, 0x6c, 0xd0, 0x7a, 0xd4,
	0x06, 0xaf, 0x1a, 0x1b, 0x18, 0x19, 0x82, 0xe5, 0x0a, 0xfe, 0xed, 0x83, 0x6f, 0x8d, 0x0f, 0x26,
	0x56, 0x0e, 0x71, 0xf1, 0x99, 0x5d, 0xd6, 0x72, 0xbc, 0x78, 0x9c, 0x4c, 0x8b, 0x33, 0xd5, 0x8f,
	0x8c, 0x38, 0x26, 0xae, 0xc5, 0x31, 0xd9, 0x43, 0xe2, 0x84, 0x19, 0xfc, 0x37, 0xb3, 0xec, 0x47,
	0x95, 0x25, 0xf0, 0x27, 0xd8, 0x9c, 0xe6, 0x7f, 0xba, 0x08, 0x3f, 0x6b, 0xbe, 0xbf, 0xf4, 0xef,
	0xd2, 0x0f, 0xfe, 0xdd, 0x54, 0x19, 0x31, 0x58, 0xb9, 0x70, 0xf4, 0x6f, 0x6e, 0xff, 0x77, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xef, 0x93, 0xaa, 0x36, 0xfe, 0x04, 0x00, 0x00,
}
