apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: cnp-monitoring
spec:
  selector: 
    app: prometheus-server
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 9090 