apiVersion: v1
kind: Service
metadata:
  labels:
    app: skeleton-svc-1
  name: skeleton-svc-1
  namespace: cnp-skeleton
spec:
  ports:
  - port: 8180
    protocol: TCP
    targetPort: 8180
  selector:
    app: skeleton-svc-1