apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs2
  namespace: cnp-streamer
spec:
  capacity:
    storage: 150Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: cnp-streamer
    name: nfs
  nfs:
    server: nfs-server.cnp-streamer.svc.cluster.local
    path: "/"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs
  namespace: cnp-streamer
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 150Gi